##port 는 기본 8080으로 해보자
##mysql setting
#spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
#spring.datasource.url=jdbc:mysql://db-jbnm7-kr.vpc-pub-cdb.ntruss.com:3306/studydb?serverTimezone=Asia/Seoul
#spring.datasource.username=study
#spring.datasource.password=bitcamp123!@#
#
##mybatis setting
#mybatis.type-aliases-package=myshop.data
#mybatis.mapper-locations=/mapper/**/*.xml

#port-기본은 8080
server:
  port: 9003
  
#mysql
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://db-jbnm7-kr.vpc-pub-cdb.ntruss.com:3306/studydb?serverTimezone=Asia/Seoul
    username: study
    password: bitcamp123!@#
    
#mybatis
mybatis:
  type-aliases-package: data.dto
  mapper-locations:
  - /mapper/**/*.xml